### ISSUE TITLE
How is this different from Adafruit's GFX library?

### ISSUE THREAD

**Issue by marcmerlin** [Jorgen-VikingGod/FastLED-GFX#3]
Sorry for the dumb question, but my understanding was that the GFX library was backend independent and that you use C++ inheritance to subclass it with whatever hardware you're trying to support (which is what Adafruit::Neomatrix does).
Basically the idea is that in theory you don't have to fork it to support other hardware (except if you want more than 16bit color for drawing primitives, but it's good enough for me).
As you know, I ported Neomatrix with GFX support to FastLED, but I was curious what your port has, that GFX does not, in case I may want to import some of your code's functionality too.

Also, do you have example/cool demo code that uses this library and https://github.com/Jorgen-VikingGod/LEDMatrix  (by that, I don't mean drawing a few lines and circles, I did see that code. I was thinking about cooler demos in case you had written any) ?

**Comment by Jorgen-VikingGod** [comment]
Hi Marc,
It is just a minor change - to put in CRGB instead of uint16_t for colors.
Everything else is just the same. I wanted to have it FastLED compatible in the interface.
But I think you do not need this changes, you can also pass the color as 16bit instead of 24bit, if it is enough for you.
But I found it really handy to use the CRGB type from FastLED to have the big dynamic range and flickerless lights (mainly if you have small changes in the dark)

**Comment by marcmerlin** [comment]
Sorry, I forgot to reply. Yeah, that makes sense.
Just FYI, you can display CRGB via Adafruit NeoMatrix (and also FastLED NeoMatrix) with this little hack:  matrix->setPassThruColor(color.red*65536 + color.green*256 + color.blue)
like here:
https://github.com/marcmerlin/AnimatedGIFs/blob/master/AnimatedGIFs.ino#L147
but I agree that it would have been nice if the GFX interfaces offered native 24bit support.
Thankfully with the passthrough hack, I still get 24bit color with the native GFX lib
